openapi: 3.0.0
info:
  title: GEDB Api
  version: '0.1'
  description: 'API for accessing and changing GEDB data.  This includes retrieving and adding Product data.  Retrieving and adding Contract Data. '
servers:
  - url: 'http://localhost:3100'
    description: dev
paths:
  '/products/{category}/{date}':
    parameters:
      - schema:
          type: string
        name: category
        in: path
        required: true
      - schema:
          type: string
        name: date
        in: path
        required: true
    get:
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/product'
              examples:
                example-1: {}
                example-2: {}
                example-3: {}
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/product'
              examples:
                example-1: {}
      operationId: get-products-for-category-date
      tags:
        - product endpoints
      description: Get product list for given category and date from master table
      parameters: []
  '/products/{product_code}/{date}/child-products':
    parameters:
      - schema:
          type: string
        name: product_code
        in: path
        required: true
      - schema:
          type: string
        name: date
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  parent_product_code:
                    type: string
                    description: product code
                    example: MTM
                  parent_product_name:
                    type: string
                    example: Month to Month
                  child_product_code:
                    type: string
                  child_product_name:
                    type: string
                  base_or_option:
                    type: string
                  claims_running_in_days:
                    type: string
                  allowable_number_of_people:
                    type: string
                  category:
                    type: string
                  minimum_purchase_number:
                    type: string
                  minimum_purchase_unit_quantity:
                    type: string
                  product_offering_name:
                    type: string
                  offer_start_date:
                    type: string
                  offer_end_date:
                    type: string
                  commodity_status:
                    type: string
                  commodity_combination_code:
                    type: string
                  start_date:
                    type: string
                  end_date:
                    type: string
                required:
                  - parent_product_code
              examples:
                example-1: {}
      operationId: get-child-products-for-category-date
      description: Get all child products given the product_code and date using the ParentProductLink table
  '/products/{product_code}/{date}/set-products':
    parameters:
      - schema:
          type: string
        name: product_code
        in: path
        required: true
      - schema:
          type: string
        name: date
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  commoditiy_combination_code:
                    type: string
                  availability_start_date:
                    type: string
                  availability_end_date:
                    type: string
                  product_code:
                    type: string
                  product_name:
                    type: string
                  base_or_option:
                    type: string
                  end_date:
                    type: string
                  start_date:
                    type: string
                  commodity_combination_code:
                    type: string
                  commodity_status:
                    type: string
                  offer_end_date:
                    type: string
                  offer_start_date:
                    type: string
                  product_offering_name:
                    type: string
                  minimum_purchase_unit_quantity:
                    type: string
                  minimum_purchase_number:
                    type: string
                  category:
                    type: string
                  allowable_number_of_people:
                    type: string
                  claims_running_in_days:
                    type: string
      operationId: get-products-product_code-date-set-products
      description: Get all the Set of products available to purchase given a product_code and date using the ProductCombinationSupplyMaster table
components:
  schemas:
    product:
      title: product
      type: object
      properties:
        commodity_status:
          type: string
        offer_end_date:
          type: string
        offer_start_date:
          type: string
        Product_offering_name:
          type: string
        minimum_purchase_unit_quantity:
          type: string
        minimum_purchase_number:
          type: string
        category:
          type: string
        allowable_number_of_people:
          type: string
        claims_running_in_days:
          type: string
        base_or_option:
          type: string
        product_name:
          type: string
          example: Month to Month
        product_code:
          type: string
          description: product code
          example: MTM
      required:
        - product_code
        - product_name
  securitySchemes:
    app_id:
      name: appid
      type: apiKey
      in: query
      description: ''
  parameters:
    category:
      name: category
      in: query
      description: '**ProductCategory**, *Example: monthly*. The category of a product. Must use with `date`.'
      schema:
        type: string
      required: true
    date:
      name: date
      in: query
      description: '**Date** for which Product offering should be valid'
      schema:
        type: string
      required: true
