openapi: 3.0.0
info:
  title: GEDB Api
  version: '0.1'
  description: 'API for accessing and changing GEDB data.  This includes retrieving and adding Product data.  Retrieving and adding Contract Data. '
  contact:
    email: test@email.com
servers:
  - url: 'http://localhost:3100'
    description: dev
paths:
  /products:
    parameters: []
    get:
      summary: GET Products and Post Product endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/product'
              examples:
                example-1: {}
                example-2: {}
                example-3: {}
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/product'
              examples:
                example-1: {}
      operationId: get-products-for-category-date
      description: Get product list for given category and date from master table
      parameters:
        - schema:
            type: string
          in: query
          name: category
          required: true
        - schema:
            type: string
          in: query
          name: date
          required: true
      tags:
        - product endpoints
    post:
      summary: ''
      operationId: post-products
      responses:
        '200':
          description: OK
      description: To register parent product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'
        description: ''
      tags:
        - product endpoints
  /products/child-products:
    parameters: []
    get:
      summary: GET Child Products endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    parent_product_code:
                      type: string
                      description: product code
                      example: MTM
                    parent_product_name:
                      type: string
                      example: Month to Month
                    child_product_code:
                      type: string
                    child_product_name:
                      type: string
                    base_or_option:
                      type: string
                    claims_running_in_days:
                      type: string
                    allowable_number_of_people:
                      type: string
                    category:
                      type: string
                    minimum_purchase_number:
                      type: string
                    minimum_purchase_unit_quantity:
                      type: string
                    product_offering_name:
                      type: string
                    offer_start_date:
                      type: string
                    offer_end_date:
                      type: string
                    commodity_status:
                      type: string
                    commodity_combination_code:
                      type: string
                    start_date:
                      type: string
                    end_date:
                      type: string
                  required:
                    - parent_product_code
                    - child_product_code
              examples:
                example-1: {}
      operationId: get-child-products-for-parent-date
      description: Get all child products given the product_code and date using the ParentProductLink table
      tags:
        - product endpoints
      parameters:
        - schema:
            type: string
          in: query
          name: parent_product_code
        - schema:
            type: string
          in: query
          name: date
    post:
      summary: ''
      operationId: post-products-parent_product_code-date-child_product_code
      responses:
        '200':
          description: OK
      description: Registering a child product(support for multiple child products) to a parent product (including a pattern without a parent)
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  parent_product_code:
                    type: string
                  chld_product_codes:
                    type: array
                    items:
                      type: string
                  min_purchase_quantity_groups:
                    type: array
                    items:
                      type: integer
                  period_groups:
                    type: array
                    items:
                      type: object
                      properties:
                        start_date:
                          type: string
                        end_date:
                          type: string
                      required:
                        - start_date
                        - end_date
                required:
                  - parent_product_code
                  - chld_product_codes
                  - min_purchase_quantity_groups
                  - period_groups
      tags:
        - product endpoints
  /products/products-set:
    parameters: []
    get:
      summary: GET Set Products endpoint
      tags:
        - product endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    commoditiy_combination_code:
                      type: string
                    availability_start_date:
                      type: string
                    availability_end_date:
                      type: string
                    product_code:
                      type: string
                    product_name:
                      type: string
                    base_or_option:
                      type: string
                    end_date:
                      type: string
                    start_date:
                      type: string
                    commodity_combination_code:
                      type: string
                    commodity_status:
                      type: string
                    offer_end_date:
                      type: string
                    offer_start_date:
                      type: string
                    product_offering_name:
                      type: string
                    minimum_purchase_unit_quantity:
                      type: string
                    minimum_purchase_number:
                      type: string
                    category:
                      type: string
                    allowable_number_of_people:
                      type: string
                    claims_running_in_days:
                      type: string
                  required:
                    - commoditiy_combination_code
                    - product_code
      operationId: get-products-product_code-date-set-products
      description: Get all the Set of products available to purchase given a product_code and date using the ProductCombinationSupplyMaster table
      parameters:
        - schema:
            type: string
          in: query
          name: product_code
          required: true
        - schema:
            type: string
          in: query
          name: date
          required: true
    post:
      summary: ''
      operationId: post-products-products-set
      responses:
        '200':
          description: OK
      description: Register a set of child products (including patterns without parents)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                parent_product_code:
                  type: string
                child_product_codes:
                  type: array
                  items:
                    type: string
                periods:
                  type: array
                  items:
                    type: object
                    properties:
                      offer_start_date:
                        type: string
                      offer_end_date:
                        type: string
                    required:
                      - offer_start_date
                      - offer_end_date
              required:
                - parent_product_code
                - child_product_codes
  /products-no-sets:
    get:
      summary: GET No-Set Products endpoint
      tags:
        - product endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/product'
      operationId: get-products
      description: Returns a list of the parent with no set items in the parent product of specified product category.
      parameters:
        - schema:
            type: string
          in: query
          name: category
          required: true
        - schema:
            type: string
          in: query
          name: date
          required: true
    parameters: []
  /products-parent-child-combo:
    get:
      summary: GET Parent-Child Combination endpoint
      tags:
        - product endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    parent_product_code:
                      type: string
                    child_product_code:
                      type: string
                    commodity_combination_code:
                      type: string
                  required:
                    - parent_product_code
                    - child_product_code
      operationId: get-products-parent-child-combo
      description: Returns a list of available ways to purchase the specified parent and child (group) (single item combination of parent and child + child set combination).
      parameters:
        - schema:
            type: string
          in: query
          name: parent_product_code
          required: true
        - schema:
            type: string
          in: query
          name: number_of_parent_applications
          required: true
        - schema:
            type: string
          in: query
          name: child_product_code
          required: true
        - schema:
            type: string
          in: query
          name: number_of_child_applications
          required: true
        - schema:
            type: string
          in: query
          name: date
          required: true
  /products/products-combination:
    get:
      summary: GET Product-Combination endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  can_register:
                    type: boolean
                  reason:
                    type: string
                required:
                  - can_register
              examples:
                example-1: {}
      operationId: get-products-kk
      description: Returns whether or not the specified set of product codes can be registered (it is better to return the reason(s) why they cannot be registered).
      parameters:
        - schema:
            type: string
          in: query
          name: commodity_combination_code
          required: true
      tags:
        - product endpoints
    parameters: []
  '/contract/{company_code}':
    parameters:
      - schema:
          type: string
        name: company_code
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - contract endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/contract'
      operationId: get-contract-contract_code
      description: Get the currently active contract list given the company code.  Optional parameter of date can be set to get the contracts active on a certain date only.
      parameters:
        - schema:
            type: string
          in: query
          name: date
          description: Optional parameter to get the contracts active for a specific date
  '/contract-history/{contract_code}':
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-contract-history
      description: 'Get the history of the contract, given the contract code (including the application number)'
    parameters:
      - schema:
          type: string
        name: contract_code
        in: path
        required: true
components:
  schemas:
    product:
      title: product
      type: object
      properties:
        commodity_status:
          type: string
        product_code:
          type: string
          description: product code
          example: MTM
        product_name:
          type: string
          example: Month to Month
        base_or_option:
          type: string
        claims_running_in_days:
          type: string
        allowable_number_of_people:
          type: string
        category:
          type: string
        minimum_purchase_number:
          type: string
        minimum_purchase_unit_quantity:
          type: string
        Product_offering_name:
          type: string
        offer_start_date:
          type: string
        offer_end_date:
          type: string
      required:
        - product_code
        - minimum_purchase_number
        - offer_start_date
        - offer_end_date
    contract:
      title: contract
      type: object
      properties:
        quantity:
          type: integer
        application_form_internal_number:
          type: string
        latest_flag:
          type: string
        commodity_combination_code:
          type: string
        commodity_contracts_end:
          type: string
        commodity_contract_start_date:
          type: string
        contract_end_date:
          type: string
        contract_start_date:
          type: string
        status:
          type: string
        available_for_loan:
          type: boolean
        presence_of_fixed_IP:
          type: boolean
        installation_location:
          type: string
        product_code:
          type: string
        contract_code:
          type: string
        sequence_number:
          type: integer
      x-tags:
        - contract endpoints
    application:
      title: application
      type: object
      properties:
        application_form_internal_number:
          type: string
        project_name:
          type: string
        contract_date:
          type: string
        ordering_division:
          type: string
        billing_frequency:
          type: string
        automatic_updating:
          type: string
  securitySchemes:
    app_id:
      name: appid
      type: apiKey
      in: query
      description: ''
  parameters:
    category:
      name: category
      in: query
      description: '**ProductCategory**, *Example: monthly*. The category of a product. Must use with `date`.'
      schema:
        type: string
      required: true
    date:
      name: date
      in: query
      description: '**Date** for which Product offering should be valid'
      schema:
        type: string
      required: true
tags:
  - name: product endpoints
    description: API related to product functions like get post
